import React from 'react'
import { SectionList, StyleSheet, Text, View } from 'react-native'

const menuItemsToDisplay = [
    {
      title: 'Appetizers',
      data: [
        { name: 'Hummus', price: '$5.00' },
        { name: 'Moutabal', price: '$5.00' },
        { name: 'Falafel', price: '$7.50' },
        { name: 'Marinated Olives', price: '$5.00' },
        { name: 'Kofta', price: '$5.00' },
        { name: 'Eggplant Salad', price: '$8.50' },
      ],
    },
    {
      title: 'Main Dishes',
      data: [
        { name: 'Lentil Burger', price: '$10.00' },
        { name: 'Smoked Salmon', price: '$14.00' },
        { name: 'Kofta Burger', price: '$11.00' },
        { name: 'Turkish Kebab', price: '$15.50' },
      ],
    },
    {
      title: 'Sides',
      data: [
        { name: 'Fries', price: '$3.00', id: '11K' },
        { name: 'Buttered Rice', price: '$3.00' },
        { name: 'Bread Sticks', price: '$3.00' },
        { name: 'Pita Pocket', price: '$3.00' },
        { name: 'Lentil Soup', price: '$3.75' },
        { name: 'Greek Salad', price: '$6.00' },
        { name: 'Rice Pilaf', price: '$4.00' },
      ],
    },
    {
      title: 'Desserts',
      data: [
        { name: 'Baklava', price: '$3.00' },
        { name: 'Tartufo', price: '$3.00' },
        { name: 'Tiramisu', price: '$5.00' },
        { name: 'Panna Cotta', price: '$5.00' },
      ],
    },
  ];

const Item = ({ name, price}) => (
    <View style={menuStyles.itemStyle}>
        <Text style={menuStyles.itemText}>{name}</Text>
        <Text style={menuStyles.itemText}>{price}</Text>
    </View>
)

const Separator = () => <View style={menuStyles.separator}></View>



const SectionListPractice = () => {

    const renderItem = ({ item }) => <Item name={item.name} price={item.price}></Item>

    const renderSectionHeader = ({ section: { title } }) => (
        <Text style={menuStyles.sectionHeader}>{title}</Text>
    )

    const Footer = () => <View >
        <Text style={menuStyles.footerText}>All rights reserved by Little Lemon,2022</Text>
    </View>

    return (
        <View style={menuStyles.container}>
            <Text>Menu Item(Section List)</Text>
            <SectionList
                sections={menuItemsToDisplay}
                keyExtractor={(item,index) => item+index}
                renderItem={renderItem}
                renderSectionHeader={renderSectionHeader} //here "render" used in props will render every time for new element of that array.header should be used every time but footer should be used only one time thats why header is rendered every time with renderSectionHeader but footer is not generated by renderSectionFooter rather ListFooterComponent ensures one time creation of footer!
                ListFooterComponent={Footer}
                ItemSeparatorComponent={Separator}
                
            ></SectionList>
        </View>
    )
}
const menuStyles = StyleSheet.create({
    container: {
        flex: 0.95,
    },
    innerContainer: {
        paddingHorizontal: 40,
        paddingVertical: 20,
        backgroundColor: '#333333',
    },
    sectionHeader: {
        backgroundColor: '#fbdabb',
        color: '#333333',
        fontSize: 34,
        flexWrap: 'wrap',
        textAlign: 'center',
    },
    itemText: {
        color: '#F4CE14',
        fontSize: 25,
    },
    separator: {
        borderBottomWidth: 1,
        borderColor: '#EDEFEE',
    },
    footerText: {
        color: '#EDEFEE',
        fontSize: 20,
        flexWrap: 'wrap',
        textAlign: 'center',
    },
    itemStyle:{
        flexDirection:'row',
        justifyContent:"space-between",
        padding:20
    }
});
export default SectionListPractice